"use client";
import Link from "next/link";
import {useState} from "react";
export interface PlanView{id:string;name:string;description:string|null;subject:string;tier:string;priceMonthly:number;priceYearly:number;checksLimit:number}
export function PricingClient({plans,activePlanIds,loggedIn,testMode=false}:{plans:PlanView[];activePlanIds:string[];loggedIn:boolean;testMode?:boolean}){
 const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState("");
 async function subscribe(planId:string){setBusy(planId);setError("");try{const res=await fetch("/api/billing/create-payment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({planId,period:"month"})});const data=await res.json();if(!res.ok)throw new Error();window.location.assign(data.confirmationUrl);}catch{setError("Не удалось открыть оплату. Попробуйте ещё раз.");setBusy(null)}}
 const plan=plans.find(p=>p.id==="all");if(!plan)return <p>Подписка скоро появится.</p>;
 return <><article className="early-access-card"><div className="early-access-copy"><span className="early-access-badge">ЦЕНА РАННЕГО ДОСТУПА</span><h2>Одна подписка.<br/>Все ваши материалы.</h2><p>Математика и информатика в одной библиотеке. Мы пополняем её готовыми комплектами, чтобы на подготовку к уроку уходило меньше времени.</p><ul><li>Все опубликованные комплекты по двум предметам</li><li>Презентации, рабочие листы, ДЗ и проверочные работы</li><li>Новые материалы, выходящие за время подписки</li><li>Доступ с любого устройства через ваш аккаунт</li></ul></div><div className="early-access-price"><span className="old-price" aria-label="Планируемая обычная цена: 1 000 рублей">1 000 ₽</span><div className="plan-price">{Math.round(plan.priceMonthly/100)} ₽<small> / месяц</small></div><p>Пока библиотека пополняется</p>{loggedIn?<button className="btn btn-blue" disabled={busy!==null} onClick={()=>subscribe("all")}>{busy?"Открываем оплату…":testMode?"Протестировать подписку":activePlanIds.includes("all")?"Продлить на месяц":"Открыть все материалы"}</button>:<Link className="btn btn-blue" href="/login?callbackUrl=/pricing">Войти и оформить подписку</Link>}<small>{testMode?"Тестовая оплата · без списания денег":"Один календарный месяц доступа"}</small><small>Разовая оплата. Без автосписаний.</small>{activePlanIds.includes("all")&&<span className="plan-active">Ваша подписка активна</span>}</div></article>{error&&<p role="alert" className="payment-error">{error}</p>}</>;
}
