"use client";
import { useState } from "react";
import {catalogTaxonomy} from "@/lib/catalog-taxonomy";
import Link from "next/link";
import { IconArrowRight, IconFolder } from "../_components/Icons";
type Item = { id:string; slug:string; title:string; subject:string; course:string|null; courseSlug:string|null; audience:string|null; previewPath:string|null; assets:{kind:string}[] };
export function ExamNavigator({products}:{products:Item[]}) {
 const [subject,setSubject]=useState("math");
 const [selected,setSelected]=useState<number|null>(null);
 const number = (p:Item) => Number(p.course?.match(/Задание\s*(\d+)/i)?.[1] ?? p.courseSlug?.match(/-(\d+)$/)?.[1] ?? 0);
 const subjectProducts=products.filter(p=>p.subject===subject);
 return <main className="exam-page"><span className="eyebrow">ОТ ЗАДАНИЯ — К ГОТОВОМУ УРОКУ</span><h1>Навигатор по ЕГЭ</h1><p>Выберите предмет и номер задания. Мы покажем комплекты по этой теме.</p><div className="exam-subjects">{[["math","Математика"],["informatics","Информатика"]].map(([id,label])=><button key={id} aria-pressed={subject===id} onClick={()=>{setSubject(id);setSelected(null)}}>{label}<span>Комплектов: {products.filter(p=>p.subject===id).length}</span></button>)}</div><div className="exam-legend"><span><i/>Есть материалы</span><span>Остальные темы постепенно пополняются</span></div><div className="exam-numbers">{catalogTaxonomy[subject].map(({number:n,title})=>{const count=subjectProducts.filter(p=>number(p)===n).length;return <button key={n} title={title} aria-label={`Задание ${n}. ${title}`} className={`${count?"has-materials":""} ${selected===n?"selected":""}`} aria-expanded={selected===n} aria-controls="exam-results" onClick={()=>setSelected(selected===n?null:n)}><small>ЗАДАНИЕ</small><b>{String(n).padStart(2,"0")}</b><span>{count ? `Комплектов: ${count}` : "Скоро"}</span></button>})}</div><section id="exam-results" className="exam-results" aria-live="polite">{selected===null?<div className="exam-prompt"><IconFolder size={30}/><h2>С какого задания начнём?</h2><p>Номера с зелёной отметкой уже содержат материалы.</p></div>:<><div className="catalog-heading"><h2>Задание {selected} · {catalogTaxonomy[subject].find(t=>t.number===selected)?.title}</h2><span>{subject==="math"?"Математика":"Информатика"}</span></div>{subjectProducts.filter(p=>number(p)===selected).length ? subjectProducts.filter(p=>number(p)===selected).map(p=><Link key={p.id} href={`/catalog/${p.slug}`} className="exam-result">{p.previewPath&&<img src={`/api/preview/${p.id}`} alt=""/>}<div><small>{p.audience}</small><h3>{p.title}</h3><p>Файлов в комплекте: {p.assets.length}</p></div><span>Открыть материалы <IconArrowRight size={19}/></span></Link>):<div className="library-empty"><h3>Материалы по этому заданию готовятся</h3><p>Попробуйте номер с зелёной отметкой или откройте весь каталог.</p><Link href="/catalog" className="btn btn-outline">Все материалы</Link></div>}</>}</section></main>;
}
